---
apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
  namespace: default
type: Opaque
stringData:
  email: "admin@admin.com"  # Replace with actual email
  password: "admin123"    # Replace with actual app password
  db-password: "<>"  # Replace with actual DB password
  app-host: "demo-ecom-app-service"        # Replace with actual app host (e.g., app service name or IP)
  main-db: "<>"  # Replace with actual DB host
  db-user: "postgres"              # Replace with actual DB user
  db-name: "evershop"              # Replace with actual DB name