---
apiVersion: batch/v1
kind: Job
metadata:
  name: evershop-db-create
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: psql-client
        image: postgres:latest
        command: ["psql"]
        args:
          - "-h"
          - "$(DB_HOST)"
          - "-U"
          - "postgres"
          - "-p"
          - "5432"
          - "-c"
          - "CREATE DATABASE evershop;"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key:  db-password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key:  main-db
      restartPolicy: Never
  backoffLimit: 4
---