---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bootstrap-scripts
  namespace: default
data:
  update_widget.sql: |
    UPDATE widget
    SET settings = '{
      "text": "[{\"id\":\"r__63dcb2ab-c2a4-40fc-a995-105bf1484b06\",\"size\":1,\"columns\":[{\"id\":\"c__354832f1-6fe1-4845-8cbb-7e094082810e\",\"size\":1,\"data\":{\"time\":1725374404621,\"blocks\":[{\"id\":\"KRtRWBBVvm\",\"type\":\"raw\",\"data\":{\"html\":\"&lt;div style=\\\"height: 500px; margin-top: -3rem; background: linear-gradient(135deg, #aad3ff, #0056b3); display: flex; align-items: center; justify-content: center;\\\"&gt;\\n  &lt;div style=\\\"display: flex; align-items: center; max-width: 1200px; width: 100%; padding: 0 20px;\\\"&gt;\\n    &lt;div style=\\\"flex: 1; text-align: center;\\\"&gt;\\n      &lt;svg width=\\\"300\\\" height=\\\"300\\\" viewBox=\\\"0 0 128 146\\\" fill=\\\"none\\\" xmlns=\\\"http://www.w3.org/2000/svg\\\" style=\\\"fill: #0056b3; color: #0056b3;\\\"&gt;\\n        &lt;path d=\\\"M32.388 18.0772L1.15175 36.1544L1.05206 72.5081L0.985596 108.895L32.4213 127.039C49.7009 137.008 63.9567 145.182 64.1228 145.182C64.289 145.182 72.8956 140.264 83.2966 134.283C93.6644 128.268 107.82 120.127 114.732 116.139L127.26 108.895V101.119V93.3102L126.529 93.7089C126.097 93.9415 111.941 102.083 95.06 111.853C78.1459 121.622 64.156 129.531 63.9567 129.498C63.724 129.431 52.5587 123.051 39.1005 115.275L14.6099 101.152V72.5746V43.9967L25.6756 37.6165C31.7234 34.1274 42.8223 27.7472 50.2991 23.4273C57.7426 19.1073 63.9899 15.585 64.1228 15.585C64.2557 15.585 72.9288 20.5362 83.3963 26.5841L113.902 43.9967L118.713 41.1657L127.26 36.1544L113.902 28.5447C103.334 22.2974 64.3554 -0.033191 64.0231 3.90721e-05C63.8237 3.90721e-05 49.568 8.14142 32.388 18.0772Z\\\" fill=\\\"#0056b3\\\"&gt;&lt;/path&gt;\\n        &lt;path d=\\\"M96.0237 54.1983C78.9434 64.0677 64.721 72.2423 64.4219 72.3088C64.0896 72.4084 55.7488 67.7562 44.8826 61.509L25.9082 50.543V58.4186L25.9414 66.2609L44.3841 76.8945C54.5193 82.743 63.1591 87.6611 63.5911 87.8272C64.2557 88.0598 68.9079 85.5011 95.5585 70.1156C112.705 60.1798 126.861 51.9719 127.027 51.839C127.16 51.7061 127.227 48.1505 127.194 43.9302L127.094 36.2541L96.0237 54.1983Z\\\" fill=\\\"#0056b3\\\"&gt;&lt;/path&gt;\\n        &lt;path d=\\\"M123.771 66.7261C121.943 67.7562 107.854 75.8976 92.4349 84.8033C77.0161 93.7089 64.289 100.986 64.1228 100.986C63.9567 100.986 55.3501 96.0683 44.9491 90.0869L26.0744 79.1874L25.9747 86.8303C25.9082 92.6788 26.0079 94.5729 26.307 94.872C26.9383 95.4369 63.7241 116.604 64.1228 116.604C64.4551 116.604 126.496 80.8821 127.027 80.4169C127.16 80.284 127.227 76.7284 127.194 72.4749L127.094 64.7987L123.771 66.7261Z\\\" fill=\\\"#0056b3\\\"&gt;&lt;/path&gt;\\n      &lt;/svg&gt;\\n    &lt;/div&gt;\\n    \\n    &lt;div style=\\\"flex: 1; text-align: left; padding: 20px;\\\"&gt;\\n      <h1 style=\\\"font-size: 3.5rem; color: #fff;\\\"> Scaler Shop </h1>\\n      &lt;p style=\\\"font-size: 1.5rem; color: #fff; margin: 20px 0;\\\"&gt; We are thrilled to have you here! Explore our latest collection of trendy footwear, from everyday essentials to statement styles. Whether you are looking for comfort, elegance, or something bold, we have got the perfect pair for every occasion. &lt;/p&gt;\\n      &lt;a href=\\\"#\\\" style=\\\"display: inline-block; padding: 10px 20px; background-color: #fff; color: #0056b3; text-decoration: none; border-radius: 5px; font-weight: bold;\\\"&gt;SHOP NOW&lt;/a&gt;\\n    &lt;/div&gt;\\n  &lt;/div&gt;\\n&lt;/div&gt;\\n\"}}],\"version\":\"2.30.2\"}}]}]",
      "className": ""
    }'::jsonb
    WHERE widget_id = 4;
---
apiVersion: batch/v1
kind: Job
metadata:
  name: evershop-bootstrap
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: bootstrap-client
        image: ubuntu/postgres:latest  # Using bitnami/postgresql for psql, curl, and jq support
        command: ["/bin/bash", "-c"]
        args:
          - |
            # Install jq if not present in the image
            apt-get update && apt-get install -y jq curl
            # Define the JSON string
            json_data='{
                "product1": {
                "name": "Strutter shoes",
                "url_key": "strutter",
                "sku": "strutter",
                "images": "/assets/plv1439-White-listing.png",
                "description": "Maximum cushioning provides a comfortable ride for everyday runs. Our softest, most cushioned ride has lightweight ZoomX foam stacked on top of responsive ReactX foam in the midsole. Plus, a redesigned traction pattern offers a smooth heel-to-toe transition.",
                "meta_title": "strutter",
                "price": "384"
              },
                "product2": {
                "name": "Trefoil shoes",
                "url_key": "trefoil",
                "sku": "trefoil",
                "images": "/assets/plv1120-White-listing.png",
                "description": "Maximum cushioning provides a comfortable ride for everyday runs. Our softest, most cushioned ride has lightweight ZoomX foam stacked on top of responsive ReactX foam in the midsole. Plus, a redesigned traction pattern offers a smooth heel-to-toe transition.",
                "meta_title": "trefoil",
                "price": "198"
              },
                "product3": {
                "name": "Hacked fashion chuck taylor all star",
                "url_key": "allstar",
                "sku": "allstar",
                "images": "/assets/plv4117-Blue-listing.png",
                "description": "Maximum cushioning provides a comfortable ride for everyday runs. Our softest, most cushioned ride has lightweight ZoomX foam stacked on top of responsive ReactX foam in the midsole. Plus, a redesigned traction pattern offers a smooth heel-to-toe transition.",
                "meta_title": "allstar",
                "price": "400"
              },
                "product4": {
                "name": "Seasonal color chuck 70",
                "url_key": "chuck70",
                "sku": "chuck70",
                "images": "/assets/plv3643-Blue-listing.png",
                "description": "Maximum cushioning provides a comfortable ride for everyday runs. Our softest, most cushioned ride has lightweight ZoomX foam stacked on top of responsive ReactX foam in the midsole. Plus, a redesigned traction pattern offers a smooth heel-to-toe transition.",
                "meta_title": "chuck70",
                "price": "600"
              },
                "product5": {
                "name": "Air zoom pegasus 35",
                "url_key": "air",
                "sku": "air",
                "images": "/assets/plv1301-Red-listing.png",
                "description": "Maximum cushioning provides a comfortable ride for everyday runs. Our softest, most cushioned ride has lightweight ZoomX foam stacked on top of responsive ReactX foam in the midsole. Plus, a redesigned traction pattern offers a smooth heel-to-toe transition.",
                "meta_title": "air",
                "price": "500"
              },
                "product6": {
                "name": "Zoom",
                "url_key": "zoom",
                "sku": "zoom",
                "images": "/ citizenships/plv7836-Blue-listing.png",
                "description": "Maximum cushioning provides a comfortable ride for everyday runs. Our softest, most cushioned ride has lightweight ZoomX foam stacked on top of responsive ReactX foam in the midsole. Plus, a redesigned traction pattern offers a smooth heel-to-toe transition.",
                "meta_title": "zoom",
                "price": "499.99"
              },
                "product7": {
                "name": "Revolution 5",
                "url_key": "revolution",
                "sku": "revolution",
                "images": "/assets/plv3878-Purple-listing.png",
                "description": "Maximum cushioning provides a comfortable ride for everyday runs. Our softest, most cushioned ride has lightweight ZoomX foam stacked on top of responsive ReactX foam in the midsole. Plus, a redesigned traction pattern offers a smooth heel-to-toe transition.",
                "meta_title": "revolution",
                "price": "255"
              },
                "product8": {
                "name": "Court vision low",
                "url_key": "court",
                "sku": "court",
                "images": "/assets/plv1121-White-listing.png",
                "description": "Maximum cushioning provides a comfortable ride for everyday runs. Our softest, most cushioned ride has lightweight ZoomX foam stacked on top of responsive ReactX foam in the midsole. Plus, a redesigned traction pattern offers a smooth heel-to-toe transition.",
                "meta_title": "court",
                "price": "904"
              },
                "product9": {
                  "name": "Nike pegasus 350",
                  "url_key": "pegasus",
                  "sku": "pegasus",
                  "images": "/assets/plv7632-Green-listing.png",
                  "description": "Maximum cushioning provides a comfortable ride for everyday runs. Our softest, most cushioned ride has lightweight ZoomX foam stacked on top of responsive ReactX foam in the midsole. Plus, a redesigned traction pattern offers a smooth heel-to-toe transition.",
                  "meta_title": "pegasus",
                  "price": "411"
                },
                "product10": {
                "name": "React phantom run flyknit 2",
                "url_key": "phantom",
                "sku": "phantom",
                "images": "/assets/plv2108-Green-listing.png",
                "description": "Maximum cushioning provides a comfortable ride for everyday runs. Our softest, most cushioned ride has lightweight ZoomX foam stacked on top of responsive ReactX foam in the midsole. Plus, a redesigned traction pattern offers a smooth heel-to-toe transition.",
                "meta_title": "phantom",
                "price": "500"
              }
            }'

            # Load environment variables from Secret
            EMAIL=$(cat /mnt/secrets/email)
            PASSWORD=$(cat /mnt/secrets/password)
            APP_HOST=$(cat /mnt/secrets/app-host)
            MAIN_DB=$(cat /mnt/secrets/main-db)
            DB_USER=$(cat /mnt/secrets/db-user)
            DB_NAME=$(cat /mnt/secrets/db-name)
            PGPASSWORD=$(cat /mnt/secrets/db-password)

            echo $EMAIL
            echo $PASSWORD
            COOKIE=$(curl -c - -i --location "http://$APP_HOST:3000/admin/user/login" \
            --header "Content-Type: application/json" \
            --data-raw "{
                \"email\": \"$EMAIL\",
                \"password\": \"$PASSWORD\"
              }" | grep -i 'Set-Cookie:' | sed 's/Set-Cookie: //' | tr -d '\r\n')
            echo "$COOKIE"
            COOKIE_VALUE=$(echo "$COOKIE" | cut -d';' -f1)
            echo "$COOKIE_VALUE"

            # Extract keys and iterate through each product
            echo "$json_data" | jq -c 'to_entries[] | .value' | while IFS= read -r product; do
              name=$(echo "$product" | jq -r '.name')
              description=$(echo "$product" | jq -r '.description')
              sku=$(echo "$product" | jq -r '.sku')
              url_key=$(echo "$product" | jq -r '.url_key')
              images=$(echo "$product" | jq -r '.images')
              price=$(echo "$product" | jq -r '.price')
              
              # Run the curl command with extracted values for men category
              curl -X POST \
                http://$APP_HOST:3000/api/products \
                -H "Accept: application/json" \
                -H "Content-Type: application/json" \
                -H "Cookie: $COOKIE_VALUE;" \
                -d "{
                  \"name\": \"$name\",
                  \"description\": \"$description\",
                  \"short_description\": \"$description\",
                  \"sku\": \"$sku\",
                  \"url_key\": \"$url_key\",
                  \"meta_title\": \"$meta_title\",
                  \"meta_description\": \"Your product meta description\",
                  \"meta_keywords\": \"keywords\",
                  \"status\": 1,
                  \"price\": \"$price\",
                  \"weight\": \"1\",
                  \"qty\": \"100\",
                  \"manage_stock\": 1,
                  \"stock_availability\": 1,
                  \"group_id\": 1,
                  \"visibility\": 1,
                  \"images\": [\"$images\"],
                  \"category_id\": 3,
                  \"attributes\": [
                    {
                      \"attribute_code\": \"size\",
                      \"value\": \"2\"
                    },
                    {
                      \"attribute_code\": \"color\",
                      \"value\": [\"1\"]
                    }
                  ]
                }"

              sku="w${sku}"
              url_key="w${url_key}"
              # Run the curl command with extracted values for women category
              curl -X POST \
                http://$APP_HOST:3000/api/products \
                -H "Accept: application/json" \
                -H "Content-Type: application/json" \
                -H "Cookie: $COOKIE_VALUE;" \
                -d "{
                  \"name\": \"Styler ${name}\",
                  \"description\": \"$description\",
                  \"short_description\": \"$description\",
                  \"sku\": \"$sku\",
                  \"url_key\": \"$url_key\",
                  \"meta_title\": \"$meta_title\",
                  \"meta_description\": \"Your product meta description\",
                  \"meta_keywords\": \"keywords\",
                  \"status\": 1,
                  \"price\": \"$price\",
                  \"weight\": \"1\",
                  \"qty\": \"100\",
                  \"manage_stock\": 1,
                  \"stock_availability\": 1,
                  \"group_id\": 1,
                  \"visibility\": 1,
                  \"images\": [\"$images\"],
                  \"category_id\": 2,
                  \"attributes\": [
                    {
                      \"attribute_code\": \"size\",
                      \"value\": \"2\"
                    },
                    {
                      \"attribute_code\": \"color\",
                      \"value\": [\"1\"]
                    }
                  ]
                }"
            done

            # Run the final psql command
            PGPASSWORD="$PGPASSWORD" psql -h $MAIN_DB -U $DB_USER -d $DB_NAME -f  /mnt/scripts/update_widget.sql
        env:
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: email
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: password
        - name: APP_HOST
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: app-host
        - name: MAIN_DB
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: main-db
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: db-user
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: db-name
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: db-password
        volumeMounts:
        - name: secrets
          mountPath: /mnt/secrets
          readOnly: true
        - name: scripts
          mountPath: /mnt/scripts
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: app-credentials
      - name: scripts
        configMap:
          name: bootstrap-scripts
      restartPolicy: Never
  backoffLimit: 4